### ISSUE TITLE
Symbolic links to directories are not treated as directories

### ISSUE THREAD

**Issue by GwyndolynMarchant** [knipferrc/fm#37]
I have a symbolic link in my home directory, which is not recognized by `fm`. 

![image](https://user-images.githubusercontent.com/59987656/135167677-dde0e812-fd48-4d8b-aaf5-ec344648c8b0.png)

`file` output on the link in question:
`Templates: symbolic link to /home/gwyndolyn/Repositories/Dot-Files/Templates/`

I have replicated the problem by creating a symbolic link to a folder elsewhere (in my Documents folder, for example) and `fm` is again unable to resolve it to a directory.

System details:
* OS: EndeavourOS Linux x86_64 
* Host: iMac8,1 1.0 
* Kernel: 5.14.7-arch1-1
* Shell: fish 3.3.1

**Comment by knipferrc** [comment]
@GwyndolynMarchant Thanks for reporting the issue. I pushed up what I believe will fix this if you don't mind testing the latest version 0.5.2 and let me know if its working for you
