### ISSUE TITLE
Open files

### ISSUE THREAD

**Issue by LuisHenriqueFA14** [knipferrc/fm#38]
How can i open a selected file in vim ?

**Comment by knipferrc** [comment]
Hey @LuisHenriqueFA14 currently opening a file in an editor is not supported. Could be a nice feature to have though

**Comment by LuisHenriqueFA14** [comment]
@knipferrc I am taking a look at the code and trying to fix it too, lol.
But i have a question, do you want to keep `fm` opened when user closes the CLI editor, or `fm` can be closed after that ?

**Comment by knipferrc** [comment]
@LuisHenriqueFA14 my preference would be to keep fm opened when the CLI editor is closed

**Comment by knipferrc** [comment]
@LuisHenriqueFA14 i think I have a fix for this. Will try to get a release out for it tomorrow

**Comment by LuisHenriqueFA14** [comment]
> @LuisHenriqueFA14 i think I have a fix for this. Will try to get a release out for it tomorrow 

I'm already looking forward

**Comment by knipferrc** [comment]
Alright, 0.12.1 has been released, should be able to spawn vim now

**Comment by LuisHenriqueFA14** [comment]
Bro, i was able to open vim, but when i closed this happened:

![image](https://user-images.githubusercontent.com/72721283/149151171-513284a7-0ee3-47af-a7f1-8445ec475247.png)

**Comment by LuisHenriqueFA14** [comment]
I'm using terminal kitty so I had to change the TERM var to "xterm-256color" for it to work 👍🏻

**Comment by knipferrc** [comment]
Interesting, i'm also using kitty but have not seen that error. Awesome, glad to hear it working for you!
