### ISSUE TITLE
[Feature Request] Add Ability to Write File Path Instead of Open File

### ISSUE THREAD

**Issue by is0n** [knipferrc/fm#58]
[Lf](https://github.com/gokcehan/lf) for example has this feature that instead of opening files, it writes the path of the selected file onto a specified file.

For example, when using this Lf, if `lf -selection-path /tmp/tempfile` is used, then instead of doing something like...
```
$ $EDITOR /path/to/file
```
when opening a file, it writes the file's path to the file specified after `-selection-path`...
```
$ echo "/path/to/file" > /tmp/tempfile
$ cat /tmp/tempfile
/path/to/file
```

This is an excerpt from the `lf --help`...
> -selection-path string
        path to the file to write selected files on open (to use as open file dialog)

I request this feature as I really like your file manager and would like to use it with my neovim plugin called [fm-nvim](https://github.com/is0n/fm-nvim).

**Comment by is0n** [comment]
If `fm` is called with `-selection-path` followed by a path to a file (the file doesn’t have to exist), then whenever the user opens a file with `E` instead of doing something like…
```
$ $EDITOR /path/to/opened/file
```
it writes `/path/to/opened/file` to the file specified in the command.

**Comment by knipferrc** [comment]
Ok I think I am getting it now. So if I open FM `fm` with `-selection-path` then instead of opening the file with `E` it will write that `selection-path` to the file that is currently selected. So for example I have a file called `test.txt` currently highlighted in the tree, if I press `E`, it wont open in the $EDITOR, it will write `/path/to/some/file` to it?

**Comment by is0n** [comment]
Seems good!

**Comment by knipferrc** [comment]
Cool, that seems doable, will take a swing at it

**Comment by knipferrc** [comment]
@is0n take a look at #59 and let me know if that's what your looking for

**Comment by is0n** [comment]
Just compiled fm with the new updates and I have found that when opening a file with `E`, the opened file gets overwritten with the file path specified in `fm --selection-path`.

https://user-images.githubusercontent.com/57725322/139540619-99ed15bd-3d7d-4ead-a0cf-7c10fe985e72.mov

As mentioned before, the path of the opened file (in the case of the video, those files would be `LICENSE` or `Makefile`) would be written to the file specified in the command (in the case of the video, that would be `/tmp/tempfile`). What happened instead was that `/tmp/tempfile` replaced the contents of the opened files.

I would also like to mention that fm should close once it opens a file when `--selection-path` is used.

**Comment by knipferrc** [comment]
So your saying that the selection-path file should be created, and then the path of the selected file would be written to that newly created file, in your case, `/tmp/tempfile` would be created, and the paths would get appended to that file any time you press `E` and then each time you press `E`, it writes the path and then exits?

**Comment by is0n** [comment]
> So your saying that the selection-path file should be created

The file should only be created after the file is opened, not before so that if no file is opened, there isn't an empty file lying around.

> the paths would get appended to that file any time you press E and then each time you press E, it writes the path and then exits?

The path to the opened file would replace the contents of `/tmp/tempfile` once `E` is used and after that happens, fm would close.

**Comment by knipferrc** [comment]
Ok I think I get it now, I’ll take another swing at it

**Comment by knipferrc** [comment]
@is0n if you want to give that branch another go I updated it with what I believe to be the correct logic

**Comment by is0n** [comment]
It works perfectly! I've just [updated](https://github.com/is0n/fm-nvim/commit/769bc218cd29267429bc3862dd265624eb355897) the plugin to use your file manager.

**Comment by knipferrc** [comment]
Awesome! Will cut a release
