### ISSUE TITLE
Config file ignored on Windows

### ISSUE THREAD

**Issue by zQueal** [knipferrc/fm#77]
```bash
~/.config
❯ cat fm.yml
settings:
  borderless: true
  enable_logging: false
  enable_mousewheel: true
  pretty_markdown: true
  show_icons: false
```

Config is not loaded. Borders are still enabled, icons are enabled, etc.

**Comment by knipferrc** [comment]
To be honest I have not tested in windows. Will take a look

**Comment by knipferrc** [comment]
@zQueal is this on WSL in windows or are you running this actually inside windows?

**Comment by zQueal** [comment]
No, this is not in WSL. It's directly within the Windows terminal. I'm wondering if, under normal windows, the program doesn't look in `%AppData%/fm.yml` instead?

**Comment by knipferrc** [comment]
Alright I believe I have a solution. So on windows I wont create the config in `~/.config/fm` it will just get created in the home directory which would be `C:\Users\yourUserName\fm.yml` in which you should be able to make changes and see them reflected in `fm`. As a side note, I am adding the ability to reload the config in app through the key command `rc`. Will cut a release later on today for you to try

**Comment by knipferrc** [comment]
@zQueal released 0.12.0, let me know if that works for you

**Comment by zQueal** [comment]
Working perfectly! Thanks for the patch!

**Comment by knipferrc** [comment]
Excellent, glad to hear it!
