### ISSUE TITLE
Previewing zip, rar, mp3, webm breaks UI

### ISSUE THREAD

**Issue by mrusme** [knipferrc/fm#89]
Trying to preview either of the listed formats breaks the UI. It would be nice if fm could at least display some meta info if it's not able to give an actual preview, like the IDv3 info for mp3s or simply just file sizes and the full name of the file (as it can be too long for the list) for others.

**Comment by knipferrc** [comment]
@mrusme when you say breaks the UI what do you mean? I tried previewing all of those file types and you should be seeing a message in the secondary pane just saying "cant preview file". Are you seeing something different? If so, can you post a screenshot

**Comment by mrusme** [comment]
Yupp, I'm seeing gibberish all over the place and the UI breaks until I preview a file that is eg an image. I can post a screenshot later.

**Comment by mrusme** [comment]
I tried previewing the FCStd file, then this happend, then I moved the selection up and at least the list reappeared.

**Comment by knipferrc** [comment]
Im not familiar with FCStd files, what is contained in them?

**Comment by mrusme** [comment]
It doesn't necessarily matter. The FCStd files contain FreeCAD models, however, fm should fallback to displaying generic file info (similar to how nnn does it) when it does not know what to do with the file. This however seems like it's trying to open the file, no matter what.

**Comment by knipferrc** [comment]
@mrusme just pushed up 0.13.5 which should prevent this from breaking. For the file info, the file info is displayed in the status bar

**Comment by mrusme** [comment]
```
~ go install github.com/knipferrc/fm@latest
~
```

... when that push notification from github is quicker than goreleaser, I guess.

**Comment by mrusme** [comment]
Sorry, took some time. This is still happening with webp.

**Comment by knipferrc** [comment]
Draft PR #95 is open and addresses this

**Comment by knipferrc** [comment]
Fixed in 0.14.0
