### ISSUE TITLE
List beahviour odd

### ISSUE THREAD

**Issue by mrusme** [knipferrc/fm#90]
Talking about my folder of 800+ files, when I move down that list at some point the selected row is "below" the screen bottom, effectively making it invisible. Scrolling up two or three times brings it back into the visible area.

Another odd behavior was when I scrolled backwards (from the first position of the list on the top pressing key up). I could only scroll to roughly half of the visible list before the selection would reset to the last element again. It would basically loop from there on.

Maybe all these oddities have something to do with the UI breaking in between from trying to preview different file types.

**Comment by knipferrc** [comment]
Yeah most likely due to the broken UI when previewing files. Ill add some logic to not open files that are not supported yet which would prevent the breakage

**Comment by knipferrc** [comment]
@mrusme let me know if you still seeing this after 0.13.5 which should prevent the UI from breaking on those files

**Comment by mrusme** [comment]
Seems like this was fixed!
