### ISSUE TITLE
ctrl+d item makes highlight jump back to the top of the list

### ISSUE THREAD

**Issue by mrusme** [knipferrc/fm#92]
Ideally, the highlight would stay where it is and be placed on the next item that would follow in place of the deleted one.

**Comment by knipferrc** [comment]
Working on a large refactor and this should be addressed as part of that

**Comment by knipferrc** [comment]
Draft PR #95 is open and addresses this

**Comment by knipferrc** [comment]
Fixed in 0.14.0
