### ISSUE TITLE
ctrl+d `y` should not require CR

### ISSUE THREAD

**Issue by mrusme** [knipferrc/fm#93]
When ctrl+d a file, the input prompt that asks for confirmation should not require an additional CR, but instead accept the confirmation (or rejection) with a simple key press of y or n.

**Comment by knipferrc** [comment]
I like that, will do something like that as part of a larger refactor I’m doing

**Comment by knipferrc** [comment]
Draft PR #95 is open and addresses this

**Comment by knipferrc** [comment]
Fixed in 0.14.0
