### ISSUE TITLE
Support M1 Mac

### ISSUE THREAD

**Issue by tjoskar** [knipferrc/fm#96]
Hi,

This project looks awesome. I do however get the error message:
> knipferrc/fm crit platform darwin/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/knipferrc/fm/issues/new

I have no idea how easy/hard this is but it would be really nice.

**Comment by knipferrc** [comment]
Hey @tjoskar I dont have an M1 Mac that I can very it works on, but, if you could try installing again I have pushed a change to the install script which will hopefully allow you to install

**Comment by tjoskar** [comment]
Works nicely! Thanks!
