### ISSUE TITLE
Soft links that point to a deleted or non existent file prevents display

### ISSUE THREAD

**Issue by Hurka5** [knipferrc/fm#99]
Soft links that point to a deleted or non existent file prevents display because it can not get the stats of the file.
![kép](https://user-images.githubusercontent.com/48726730/183077611-92507510-90f0-4967-ac09-a4457be4f23b.png)

**Comment by knipferrc** [comment]
Have fixed this upstream, will do a release later on today to fix this

**Comment by Hurka5** [comment]
After the patch the display works perfectly but  the faulty soft link does not show up

**Comment by knipferrc** [comment]
Oops, ok publishing 0.15.8 which hopefully fixes it for real
